# Generated by Django 3.0.6 on 2020-06-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='type your notes here!', max_length=200)),
                ('customchoice', models.CharField(default='none', max_length=200)),
                ('m2', models.DecimalField(decimal_places=0, default=100, max_digits=30)),
                ('units', models.DecimalField(decimal_places=0, default=100, max_digits=30)),
                ('netmonth', models.DecimalField(decimal_places=2, default=100, max_digits=30)),
                ('monthlyrentm2', models.DecimalField(decimal_places=2, default=100, max_digits=30)),
                ('ideaprice', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('yearlyincome', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('factor', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('year', models.DecimalField(decimal_places=0, default=100, max_digits=30)),
                ('address', models.CharField(max_length=200)),
                ('first', models.CharField(max_length=200)),
                ('last', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monument', models.BooleanField(default=False)),
                ('builtdate', models.CharField(default='not given', max_length=200)),
                ('bezeichnung', models.CharField(default='not given', max_length=200)),
                ('denkmal_nummer', models.DecimalField(decimal_places=0, default=0, max_digits=30)),
                ('eingetragen_seit', models.CharField(default='not given', max_length=200)),
            ],
            options={
                'verbose_name': 'Data',
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
