# Generated by Django 3.0.6 on 2020-06-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='haus_kaufen_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='formdata',
            name='haus_mieten_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='formdata',
            name='wohnung_kaufen_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='formdata',
            name='wohnung_mieten_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
    ]
