# Generated by Django 3.0.6 on 2020-06-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200604_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='address',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='formdata',
            name='zip_address',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
    ]
