# Generated by Django 3.0.6 on 2020-06-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200604_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='city',
            field=models.CharField(default='not found!', max_length=200),
        ),
    ]
