# Generated by Django 3.0.5 on 2020-06-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200605_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='city_population',
            field=models.CharField(default='not found!', max_length=200),
        ),
    ]
