# Generated by Django 3.0.5 on 2020-06-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_formdata_city_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='city_population',
        ),
    ]
