# Generated by Django 3.0.5 on 2020-06-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_formdata_city_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='nearby_train_station_distance',
            field=models.CharField(default='not found!', max_length=200),
        ),
        migrations.AddField(
            model_name='formdata',
            name='nearby_train_station_duration',
            field=models.CharField(default='not found!', max_length=200),
        ),
        migrations.AddField(
            model_name='formdata',
            name='nearby_train_station_name',
            field=models.CharField(default='not found!', max_length=200),
        ),
    ]
