# Generated by Django 3.0.5 on 2020-06-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200610_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='nearby_train_station_distance',
            new_name='nearby_train_station',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='nearby_train_station_duration',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='nearby_train_station_name',
        ),
    ]
