# Generated by Django 3.0.5 on 2020-06-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20200610_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='central_distances',
            field=models.CharField(default='not found!', max_length=200),
        ),
    ]
