# Generated by Django 3.0.6 on 2020-06-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_formdata_central_distances'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='none', max_length=200)),
            ],
            options={
                'verbose_name': 'Data',
            },
        ),
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
