# Generated by Django 3.0.6 on 2020-07-19 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20200621_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
